target:
	$(CC) -o main.exe main.c utils.c

clean:
	if ls *.exe > /dev/null 2>&1; then rm *.exe; fi
	if ls *.s > /dev/null 2>&1; then rm *.s; fi
	if ls *.o > /dev/null 2>&1; then rm *.o; fi
	if ls *.i > /dev/null 2>&1; then rm *.i; fi